# Site Info
title: YABOONG
tagline: 'Yaboong''s blog'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://github.com/yaboong
logo: '/public/yaboong_logo.png'

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 3
paginate_path: '/blog/page:num'
permalink: pretty
timezone: 'Asia/Seoul'
future: true

version: 1.0.0

# About/contact
author:
  name: Yaboong
  description: <strong>developer yaboong</strong>
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
#    linkedin:
    github:    https://github.com/yaboong
    # facebook:  <hide>
    twitter:
#    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=
    email: daniel.yebon.yoo@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/yaboong'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

yaboong:
  image: /public/img/schindlers_list.jpg
  caption: 오스카 쉰들러는 흔해빠진 기회주의자요 부패한 사업가였다. 그러나 거대한 악이 세상을 점령하는 것처럼 보일 때 그 악에 대항해서 사람의 생명을 구한 것은 귀족도 지식인도 종교인도 아닌 부패한 기회주의자 오스카 쉰들러였다.
#  그의 영혼에 안식과 축복이 있기를.
#  caption: Oscar Schindler was a common opportunist and corrupt businessman.
#          But it was Oscar Schindler, a corrupt opportunist who was not a noble, an intellectual, or a religious person who saved the life of a man against the evil when the great evil seemed to occupy the world.
#          There is rest and blessing in his soul.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

